version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: film-saga-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - film-saga-network

    nginx:
        image: nginx:alpine
        container_name: film-saga-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - film-saga-network

    db:
        image: mysql:8.0
        container_name: film-saga-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - film-saga-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: film-saga-phpmyadmin
        restart: unless-stopped
        ports:
            - "91:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 64M
        networks:
            - film-saga-network
        depends_on:
            db:
                condition: service_healthy
        platform: linux/amd64

networks:
    film-saga-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
